### ISSUE TITLE
Get user email

### ISSUE THREAD

**Issue by romach3** [SocialiteProviders/Yandex#1]
Hi!
https://github.com/SocialiteProviders/Yandex/blob/master/src/Provider.php#L50
This method set email property to null.

From yandex documentation:
```
default_email
E-mail по умолчанию, предназначенный для связи с пользователем.
```
https://tech.yandex.ru/passport/doc/dg/reference/response-docpage/

Please change this method and set correct email:
```
[
   'id' => $user['id'], 'nickname' => $user['login'],
   'name' => null, 'email' => $user['default_email'], 'avatar' => null,
]
```
Thx. Sorry for my bad English ))

**Comment by DraperStudio** [comment]
Fixed with https://github.com/SocialiteProviders/Yandex/commit/cc63b885044d8b158733a5b529de32d17a5e2163 and v1.0.7 tagged
