### ISSUE TITLE
Undefined index: default_avatar_id

### ISSUE THREAD

**Issue by dotzero** [SocialiteProviders/Yandex#4]
Hello

https://github.com/SocialiteProviders/Yandex/blob/master/src/Provider.php#L59

Sometimes, Yandex don't return `default_avatar_id`. Dump of my `$user` looks like:

```
array:2 [▼
  "login" => "dotzero"
  "id" => "15216072"
]
```

**Comment by DraperStudio** [comment]
https://github.com/SocialiteProviders/Yandex/commit/5966339c8d784d7a6f411b2c667560d3bdc03622
